_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.GaussianBlur
    kernel_size: 5         # Taille du noyau (doit être impair, ex: 3, 5, 7)
    sigma: [0.1, 2.0]      # Plage de sigma (aléatoire entre 0.1 et 2.0)
  - _target_: torchvision.transforms.RandomRotation
    degrees: 10